### ISSUE TITLE
Can't run on Windows 7, No module named 'libs.resources'

### ISSUE THREAD

**Issue by bestpower** [heartexlabs/labelImg#489]
After I cloned this project, run in pycharm and installed dependency libraries. But can't run labelImg.py, because can't find file resources.py. So how can I deal with this situation?
- **OS:** Windows 7
- **PyQt version:** Python 3.6 PyQt 5.13

**Comment by vdevakko** [comment]
check out issue #475 
Regards,

**Comment by bestpower** [comment]
Thank you vdevakko. I have fixed it.
