### ISSUE TITLE
labelImg.py [IMAGE_PATH] does not work 

### ISSUE THREAD

**Issue by ahmetburakgozel** [heartexlabs/labelImg#930]
labelImg.py [IMAGE_PATH] does not work .

**Comment by ahmedibrahim0100** [comment]
I think it should be:

python labelImg.py [IMAGE_PATH] **[PRE-DEFINED CLASS FILE]**

**Comment by ahmetburakgozel** [comment]
how to use [PRE-DEFINED CLASS FILE]

**Comment by ahmedibrahim0100** [comment]
[PRE-DEFINED CLASS FILE] is the path to your classes text file.
Classes text file is the file where you store the names of classes.
For example: if I have 3 classes called: cat, dog and bird, i should have a *.txt file where they are written.
For the [IMAGE_PATH], you can leave it blank and then use the "Open dir" function from inside labelImg itself.

A live example can be as such:
python labelImg.py "" "D:\Learning\classes.txt"

**Comment by KaiquanMah** [comment]
same as @ahmedibrahim0100, within the 'anaconda prompt' (I am using a windows pc),

this works - enclosing the file path (containing spaces) using double quotes
> python labelImg.py "C:\path with spaces\fileName.jpg" "C:\pathWithoutSpaces\classes.txt" -> labelImg opens up with the image file


these do not work
> python labelImg.py C:\path^ with^ spaces\fileName.jpg C:\pathWithoutSpaces\classes.txt -> cant even open up labelImg
python labelImg.py "C:\path^ with^ spaces\fileName.jpg" C:\pathWithoutSpaces\classes.txt -> labelImg opens up but without the image file
